server:
  port: 8083
spring:
  application:
    name: TMOBILE-AUTH-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmobile
    username: root
    password: anurag

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
